### ISSUE TITLE
Software installation

### ISSUE THREAD

**Issue by YuntaoTan** [ewels/ClusterFlow#121]
Should I install bowtie manually or CF will install automatically? Or other external softwares, such as BWA? if this can be solved will be great!

**Comment by ewels** [comment]
Hi @YuntaoTan,

Cluster Flow was designed to work with environment modules on HPC systems. These are centrally installed software packages that can be dynamically loaded with commands such as `module load bowtie`.

Each CF tool wrapper has a list of environment modules that it tries to load. For example, the bowtie2 module tries to load `bowtie2` and `samtools`: https://github.com/ewels/ClusterFlow/blob/c643e04cfa89b7cfb1f6f314f4ab22b92ade7b7b/modules/bowtie2.cfmod.pl#L33

This only works if you already have the software installed as environment modules, and those names match what CF expects. You can turn off this behaviour with the config options `@ignore_modules` ([docs](http://clusterflow.io/docs/#ignore_modules)) and change the names with `@environment_module_alias` ([docs](http://clusterflow.io/docs/#environment_module_alias)).

If not using environment modules, then you need to have the software available on your system.

In our group we have migrated to using [nextflow](https://www.nextflow.io/) instead of Cluster Flow, which has built in support for conda, singularity and docker. As such, pipelines such as the ones that we're working on at https://nf-co.re/ _do_ automatically install the required software for you.

I hope this helps!

Phil
