### ISSUE TITLE
warning about undefined $GENOME

### ISSUE THREAD

**Issue by ewels** [ewels/clusterflow#15]
There's a warning about undefined `$GENOME` when launching pipelines which don't need it. This is from L891 in `cf` and a couple of other places around there. Because no genome is specified then the interpolation there is wrong. I initially thought you'd just need to make `$GENOME` an empty string, but I think it's worse than that since you'll effectively end up passing the wrong number of arguments through to the memory request function if `$GENOME` is empty. I haven't looked at this thoroughly enough to see what the right fix is but I guess you'll probably know.

**Comment by ewels** [comment]
Ok, I think that it would be cleanest to handle these cases by passing the path to the run file to the module and using that to store all required config information.

I don't really like relying on option order, so I'll use a new flag for the run file name instead.

- [ ] Make `--runfn` as a flag for each module
- [ ] Add `--runfn` parameter to the `--mem` and `--cores` commands in `cf`
- [ ] Remove the `$sim_argv ` code from `cf`
- [ ] Add the genome key (`$GENOME`) to the run file as a config parameter if it's set
- [ ] Clean up code in `star.cfmod`
- [ ] Clean up code in `samtools_sort.cfmod`

@stu2 and @s-andrews - is everyone happy with this solution? @stu2, I'll do a little bit of testing, but if you could confirm that everything still works as you expect it to after my changes, that would be brilliant.

I'll reference this issue with my commits so that they show up.

Cheers all,

Phil

**Comment by s-andrews** [comment]
I think that passing the run file is the best way to handle this but why not
simply have --mem and --cores take the runfn as an argument?

module --mem=my.run

module --cores=cores

Those are just flags at the moment so you get a free bit of data to pass
around and any module which doesn't need it can just ignore it (so you don't
need to change any existing modules).  Also by passing the run file there's
never going to be a need to add anything else as every bit of information
about the submission is therefore accessible.

Simon.

PS You may have seen that we've forked clusterflow so we can keep track of
the changes we've made locally.  I've actually been fixing a bunch of issues
we've come across (including some of the cleanup you mention in these edits)
so feel free to pull anything you like from our repository.

From:  Phil Ewels <notifications@github.com>
Reply-To:  ewels/clusterflow
<reply+007c7ae346a7e872bbcefec4aa56461a78a52233b8a43e5a92cf0000000110d0b7cd9
2a169ce02da333f@reply.github.com>
Date:  Friday, 16 January 2015 11:28
To:  ewels/clusterflow <clusterflow@noreply.github.com>
Cc:  Simon Andrews <simon@proteo.me.uk>
Subject:  Re: [clusterflow] warning about undefined $GENOME (#15)


Ok, I think that it would be cleanest to handle these cases by passing the
path to the run file to the module and using that to store all required
config information.

I don't really like relying on option order, so I'll use a new flag for the
run file name instead.
*  Make --runfn as a flag for each module
*  Add --runfn parameter to the --mem and --cores commands in cf
*  Remove the $sim_argv code from cf
*  Add the genome key ($GENOME) to the run file as a config parameter if
it's set
*  Clean up code in star.cfmod
*  Clean up code in samtools_sort.cfmod
@stu2 <https://github.com/stu2>  and @s-andrews
<https://github.com/s-andrews>  - is everyone happy with this solution?
@stu2 <https://github.com/stu2> , I'll do a little bit of testing, but if
you could confirm that everything still works as you expect it to after my
changes, that would be brilliant.

I'll reference this issue with my commits so that they show up.

Cheers all,

Phil

‹
Reply to this email directly or view it on GitHub
<https://github.com/ewels/clusterflow/issues/15#issuecomment-70241236> .

**Comment by ewels** [comment]
I don't think `--mem` and `--cores` are just flags though, Cluster Flow tries to be clever and passes in a suggested number of available cores.  For instance, in the `bismark_align` module:

```perl
if($required_cores){
	print CF::Helpers::allocate_cores($required_cores, 4, 8);
	exit;
}
```

Here, CF is passing in a suggested number of cores in the `$required_cores` variable and the module is using that number as long as it's between 4 and 8.

And yes, that was my thought about passing the run file - it effectively future proofs the system as we can put whatever information we like into there.

Great news about the CF fork! I was just chatting to @FelixKrueger about it actually, I think that you have to initiate a Pull Request to my parent repository though, I don't think I can pull it from you as such.

Phil

**Comment by ewels** [comment]
With the `h_vmem` option being removed (see https://github.com/ewels/clusterflow/issues/26) this has become even simpler. Basically just the `STAR` module calculating how much memory it needs from the reference.

I think this is all completed now anyway. Closing..
