### ISSUE TITLE
Merge BI changes into main development flow

### ISSUE THREAD

**Issue by ewels** [ewels/clusterflow#25]
@s-andrews and @FelixKrueger - it seems that I can create a Pull Request from your fork to mine, even without push permissions on your fork. It looks like this will delete a lot of my additions though, so I need to figure out how to bring your changes in without wiping everything I've done since you forked.

**Comment by s-andrews** [comment]
Yeah, I did a merge between the v0.4devel branch and master in our version
so that might mess you up until you've merged them at your end. It shouldn't
delete additions you've made through?

From:  Phil Ewels <notifications@github.com>
Reply-To:  ewels/clusterflow
<reply+007c7ae3f429a83a51357914fb9d6c7042a60ed4bf56c28292cf0000000110d0fbc69
2a169ce03410790@reply.github.com>
Date:  Friday, 16 January 2015 16:18
To:  ewels/clusterflow <clusterflow@noreply.github.com>
Cc:  Simon Andrews <simon@proteo.me.uk>
Subject:  [clusterflow] Merge BI changes into main development flow (#25)


@s-andrews <https://github.com/s-andrews>  and @FelixKrueger
<https://github.com/FelixKrueger>  - it seems that I can create a Pull
Request from your fork to mine, even without push permissions on your fork.
It looks like this will delete a lot of my additions though, so I need to
figure out how to bring your changes in without wiping everything I've done
since you forked.

‹
Reply to this email directly or view it on GitHub
<https://github.com/ewels/clusterflow/issues/25> .

**Comment by ewels** [comment]
So what happens when you look at the [pull request comparison](https://github.com/s-andrews/clusterflow/compare/ewels:v0.4devel...s-andrews:master) is that merging your fork into my 0.4devel branch treats any changes I've made since your fork as deletions. Essentially your repo takes priority.

I think that the best way to handle this is for you to merge my changes into your repository, so that my recent changes take priority over your older code where the two differ (we can do this in a new branch of your repository so that it doesn't affect your active code). Once you've pulled in my changes we then do a pull request back with everything that's left. Which should be just your changes.

Does that make sense? We need to be a little co-ordinated as to when this happens so that I don't push any new commits after you pull in my changes (or you need to give me write access to your repo so that I can do the above changes myself).

**Comment by s-andrews** [comment]
I've given you access to our fork, feel free to make a new branch and go
nuts.

From:  Phil Ewels <notifications@github.com>
Reply-To:  ewels/clusterflow
<reply+007c7ae30f15320a694d0b4270237a75a56b0e2cf44b4cfe92cf0000000110d4b3a89
2a169ce03410790@reply.github.com>
Date:  Monday, 19 January 2015 11:59
To:  ewels/clusterflow <clusterflow@noreply.github.com>
Cc:  Simon Andrews <simon@proteo.me.uk>
Subject:  Re: [clusterflow] Merge BI changes into main development flow
(#25)


So what happens when you look at the pull request comparison
<https://github.com/s-andrews/clusterflow/compare/ewels:v0.4devel...s-andrew
s:master>  is that merging your fork into my 0.4devel branch treats any
changes I've made since your fork as deletions. Essentially your repo takes
priority.

I think that the best way to handle this is for you to merge my changes into
your repository, so that my recent changes take priority over your older
code where the two differ (we can do this in a new branch of your repository
so that it doesn't affect your active code). Once you've pulled in my
changes we then do a pull request back with everything that's left. Which
should be just your changes.

Does that make sense? We need to be a little co-ordinated as to when this
happens so that I don't push any new commits after you pull in my changes
(or you need to give me write access to your repo so that I can do the above
changes myself).

‹
Reply to this email directly or view it on GitHub
<https://github.com/ewels/clusterflow/issues/25#issuecomment-70482757> .

**Comment by ewels** [comment]
Nice, thanks!

**Comment by ewels** [comment]
Pull Request initiated in https://github.com/ewels/clusterflow/pull/27

**Comment by ewels** [comment]
Done!
