### ISSUE TITLE
Clusterflow and Nextflow

### ISSUE THREAD

**Issue by machbio** [ewels/clusterflow#84]
I understand that Clusterflow is a workflow manager of its own and Nextflow is a workflow manager thats gaining attention and development efforts.

I also noticed you ( @ewels  ) have started coding up nextflow workflows - https://github.com/ewels/NGI-RNAseq

Is it conceivable that in future - we can write Nextflow Workflows and integrate them in Clusterflow Workflows.

**Comment by ewels** [comment]
Hi @machbio,

You're absolutely right - the two platforms have different strengths and weaknesses. Since writing Cluster Flow I have moved to a more high throughput centre where the flexibility of Cluster Flow isn't as important and it's good to have a more robust pipeline (eg. with the ability to restart mid-way).

Whilst it would be nice to make the two compatible, I don't think it will happen. I previously [looked into](https://github.com/ewels/clusterflow/issues/78) making Cluster Flow understand CWL (Common Workflow Language) which would go towards this aim, but it was a lot of work. The architecture of Cluster Flow and NextFlow is also quite different - nextflow pipelines tend to be standalone and exist in a single file. Cluster Flow modules and pipelines are more mix and match.

Anyway, sorry, but short answer is not any time soon.

Phil
